### ISSUE TITLE
Font issue on _ Event Card 

### ISSUE THREAD

**Issue by Saieshfitpager** [Saieshfitpager/IR-App#2]
**Fonts are different here** 
1. Card Title 
2. Card_ date & Venue Label 
3. Ratings Text 
4. Price Tag

![Screenshot 2024-10-22 at 4 00 16 PM](https://github.com/user-attachments/assets/95b4386e-e7d2-4c87-99a8-84ec9deca723)

**Comment by HardikSJain** [comment]
Done
