### ISSUE TITLE
Homepage issues 

### ISSUE THREAD

**Issue by Saieshfitpager** [Saieshfitpager/IR-App#7]
![Screenshot 2024-10-24 at 4 40 25 PM](https://github.com/user-attachments/assets/2aa88e2b-f1b3-4ded-8fd8-703bd4ed2204)
Reference (left side is design , right side is developed app)

1. Category Line font size looks different 
2. Arrow is missing 

3. Padding left of "Event in 67days" isnt correct , also padding top and padding bottom
4. 3rd Line which consists of "category name" and "person's name" , here "person's name & icon" is missing.

**Comment by Saieshfitpager** [comment]
The carousel , elements style looks different 

![Screenshot 2024-10-24 at 4 44 29 PM](https://github.com/user-attachments/assets/c228b967-8dba-4d71-b73b-f0eca7a9b88f)

**Comment by HardikSJain** [comment]
The My booking card design is changed, and will be implemented in the upcoming release. 
and the color of the scroll indicator is fixed.
